DROP TABLE CALENDAR
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_CAL;

CREATE TABLE CALENDAR(
	SEQ NUMBER(8) PRIMARY KEY,
	ID VARCHAR2(50) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	RDATE VARCHAR2(12) NOT NULL,
	WDATE DATE NOT NULL
);

CREATE SEQUENCE SEQ_CAL
START WITH 1
INCREMENT BY 1;

ALTER TABLE CALENDAR
ADD CONSTRAINT FK_CAL_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);


SELECT SEQ, ID, TITLE, CONTENT, RDATE, WDATE
 					--SUBSTR(RDATE, 1 , 8) 년,월,일 까지 가지고와서 오름차순으로 정렬 한 후 앞에 순번을 매겨줌	
FROM ( SELECT ROW_NUMBER()OVER(PARTITION BY SUBSTR(RDATE, 1 , 8)ORDER BY RDATE ASC) AS RNUM,
			SEQ, ID, TITLE, CONTENT, RDATE, WDATE
	   FROM CALENDAR
	   WHERE ID='aaa' AND SUBSTR(RDATE, 1, 6)='202007' )	
	   --SUBSTR(RDATE, 1, 6)년,월 까지 가지고와서 같은 달의 데이터를 찾아준다
WHERE RNUM BETWEEN 1 AND 5; 	--5개까지 가지고와서 보여지는 달력의 칸에 표시



SELECT SEQ, ID, TITLE, CONTENT, RDATE, WDATE 
FROM CALENDAR 
WHERE RDATE LIKE'20200818%'
ORDER BY WDATE ASC;
