


SELECT SEQ, ID, REF,STEP,DEPTH,TITLE,CONTENT,WDATE,DEL,READCOUNT
FROM (SELECT ROW_NUMBER()OVER(ORDER BY REF DESC, STEP ASC) AS RNUM,
		SEQ, ID, REF,STEP,DEPTH,TITLE,CONTENT,WDATE,DEL,READCOUNT
	  FROM BBS
	  
	  /*검색 QUery */
	  ORDER BY REF DESC, STEP ASC)
WHERE RNUM >= 1 AND RNUM <=7;