CREATE TABLE COFFEEMENU(
	COFFEE VARCHAR2(30) PRIMARY KEY,
	SHOT NUMBER(20),
	TALL NUMBER(20),
	GRANDE NUMBER(20)
);

INSERT INTO COFFEEMENU(COFFEE,SHOT,TALL,GRANDE)
VALUES('오늘의 커피'
,2500
,3000
,3500);

select*FROM COFFEEMENU;