CREATE TABLE ORDERCOFFEE(
	SEQ NUMBER(10),
	ID VARCHAR2(20),
	COFFEE VARCHAR2(30),
	C_SIZE VARCHAR2(30),
	SYRUP VARCHAR2(30),
	OTHER VARCHAR2(30),
	COUNT_C NUMBER(10)
);


ALTER TABLE ORDERCOFFEE
ADD CONSTRAINT FK_ID2 FOREIGN KEY(ID)
REFERENCES COFMEMBER(ID);

CREATE SEQUENCE ORDER_SEQ  
INCREMENT BY 1           
START WITH 1             
MAXVALUE 100;

DROP TABLE ORDERCOFFEE;

select*FROM ORDERCOFFEE;

DELETE FROM ORDERCOFFEE
WHERE ID = 'aaa';
