CREATE TABLE ORDERCOFFEE(
	ID VARCHAR2(20),
	COFFEE VARCHAR2(30),
	C_SIZE VARCHAR2(30) NOT NULL,
	SYRUP VARCHAR2(30),
	OTHER VARCHAR2(10)
);

ALTER TABLE ORDERCOFFEE
ADD CONSTRAINT FK_KEY FOREIGN KEY(ID)
REFERENCES COFMEMBER(ID);


ALTER TABLE ORDERCOFFEE
ADD CONSTRAINT FK_KEY_2 FOREIGN KEY(COFFEE)
REFERENCES COFFEEMENU(COFFEE);