
CREATE TABLE ACCOUNTBOOK(
	SEQ NUMBER(8),
	ID VARCHAR2(30),    --외래키
	IO_KIND VARCHAR2(1), -- 수입/지출 구분
	AMOUNT NUMBER(9),	-- 금액
	CONTENT VARCHAR2(200),	-- 내용
	WDATE DATE	-- 입력일  SYSDATE
);


-- SEQUENCE
CREATE SEQUENCE SEQ_MEMBER_ID
INCREMENT BY 1            
START WITH 1             
MAXVALUE 100
MINVALUE 1;


-- 외래키(ID) 연결
ALTER TABLE ACCOUNTBOOK
ADD CONSTRAINT FK_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);